import "./favicon.ico";

export const metadata = {
  title: "Shibboleth Bejelentkezés",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="hu">
      <body>{children}</body>
    </html>
  );
}
